package challange;

import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;
import com.google.gson.Gson;

import okhttp3.MediaType;
import okhttp3.MultipartBody;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;

/**
 * This class implements the method to make a Http connection to a remote API
 * @see java.net.HttpURLConnection
 * @see java.io.BufferedReader
 * @see okhttp3.OkHttpClient
 */
public class Connection {
	
	/**
	 * The method {@code connectToApi} gets the json file from the API and saves it 
	 * @param 
	 * @return encoded message
	 */
	public String connectToApi(){
		String encoded = "";
		try {
			String url = "https://api.codenation.dev/v1/challenge/dev-ps/generate-data?token=a5ce48297dee45257a2b7fd105decbaad6b00a71";
			HttpURLConnection conn = (HttpURLConnection) new URL(url).openConnection();
			conn.setRequestMethod("GET");
			conn.setRequestProperty("Accept", "application/json");
			
			if (conn.getResponseCode() != 200) {
				System.out.println("Erro " + conn.getResponseCode() + " ao solicitar para " + url);
			}
			
			BufferedReader br = new BufferedReader(new InputStreamReader((conn.getInputStream())));
			String output ="";
			String line;
			while ((line = br.readLine() )!= null) {
				output += line;
			}
			conn.disconnect();
			
			Gson gson = new Gson();
			Data data = gson.fromJson(output, Data.class);
			encoded = data.cifrado;
			
			//Request the Class Files to create a Json File
			new Files().createFile(output);;
			
		} catch (MalformedURLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		return encoded;
	}
	
	/**
	 * The method {@code sendFile} submits the json file generated by the program to the Code nation API
	 * @param 
	 * @return final score for the challenge
	 */
	public String sendFile() {
		String score = "";
		OkHttpClient client = new OkHttpClient().newBuilder().build();
		MediaType mediaType = MediaType.parse("text/plain");
		RequestBody body = new MultipartBody.Builder().setType(MultipartBody.FORM).addFormDataPart("answer", "answer.json", RequestBody.create(MediaType.parse("application/octet-stream"), new File("src\\challange\\answer.json"))).build();
		Request request = new Request.Builder().url("https://api.codenation.dev/v1/challenge/dev-ps/submit-solution?token=a5ce48297dee45257a2b7fd105decbaad6b00a71").method("POST", body).build();
		Response response;
		try {
			response = client.newCall(request).execute();
			score = response.body().string();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		return score;
	}
}
